### PR TITLE
Fixes memory leak

### PR DESCRIPTION
**Pull request by ncardoso-barracuda**
There was no `lockPromiseForKey` cleanup so promises would stay there forever, even if the lock was correctly unlocked.
This became apparent in long-running scripts in which keys are constantly changing. 
This leak affects your awesome [node-fetch-cache](https://github.com/mistval/node-fetch-cache) package.

This PR adds a locking count so it can known when to perform cleanup.

### CODE REVIEW

**Comment by mistval** [comment]
Hi, thanks for the PR and apologies that I didn't notice it until now. At a glance it looks very reasonable to me, I would like to do a bit of testing with it and I will follow up over the weekend. Apologies again for the delay.

**Comment by mistval** [comment]
Thanks! I will push a new release to NPM soon, and for node-fetch-cache too.

**Comment by mistval** [comment]
node-fetch-cache@3.1.2 has been released to NPM with your fix.

**Comment by ncardoso-barracuda** [comment]
Thanks! 😄 👍

**Pull request merged**
